package:
    name: "predictmd-pdf2svg"
    version: "0.2.3"

requirements:
    build:
        - cairo
        - git
        - pkg-config
        - poppler
        - poppler-data
        - setuptools
    run:
        - cairo
        - git
        - pkg-config
        - poppler
        - poppler-data
        - setuptools

test:
    commands:
        - command -v pdf2svg
        - conda inspect linkages -p $PREFIX $PKG_NAME # [not win]
        - conda inspect objects -p $PREFIX $PKG_NAME # [osx]

about:
    home: https://github.com/DilumAluthge/predictmd-conda-recipes

extra:
    recipe-maintainers:
        - DilumAluthge
